"""phase7 ai copilot intelligence layer

Revision ID: d5f309cd42a4
Revises: '2baef409438a'
Create Date: 2026-08-20 17:54:50.313091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5f309cd42a4'
down_revision: Union[str, None] = '2baef409438a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('detected_intent', sa.String(length=100), nullable=True))
    op.add_column('conversations', sa.Column('detected_sentiment', sa.String(length=50), nullable=True))
    op.add_column('conversations', sa.Column('ai_suggested_replies', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.create_index(op.f('ix_conversations_detected_intent'), 'conversations', ['detected_intent'], unique=False)
    op.create_index(op.f('ix_conversations_detected_sentiment'), 'conversations', ['detected_sentiment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_detected_sentiment'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_detected_intent'), table_name='conversations')
    op.drop_column('conversations', 'ai_suggested_replies')
    op.drop_column('conversations', 'detected_sentiment')
    op.drop_column('conversations', 'detected_intent')
    op.drop_column('conversations', 'ai_summary')
    # ### end Alembic commands ###
