"""add_customer_blocked_fields

Revision ID: f2bd2246d1d0
Revises: '21c90ecf7c48'
Create Date: 2026-08-21 19:48:00.000000

Note (Task 11 reconciliation): every upgrade operation is guarded by an
existence check so replaying against databases where these columns were
already added manually (Task 9a service restore) is a safe no-op.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


def _cols(conn, table):
    return {c["name"] for c in inspect(conn).get_columns(table)}


def _idx(conn, table):
    return {i["name"] for i in inspect(conn).get_indexes(table)}


# revision identifiers, used by Alembic.
revision: str = 'f2bd2246d1d0'
down_revision: Union[str, None] = '21c90ecf7c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    cols = _cols(conn, "customers")
    if "is_blocked" not in cols:
        op.add_column('customers', sa.Column('is_blocked', sa.Boolean(), server_default='false', nullable=False))
    if "blocked_at" not in cols:
        op.add_column('customers', sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True))
    if "blocked_reason" not in cols:
        op.add_column('customers', sa.Column('blocked_reason', sa.String(length=500), nullable=True))
    if "ix_customers_is_blocked" not in _idx(conn, "customers"):
        op.create_index(op.f('ix_customers_is_blocked'), 'customers', ['is_blocked'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_is_blocked'), table_name='customers')
    op.drop_column('customers', 'blocked_reason')
    op.drop_column('customers', 'blocked_at')
    op.drop_column('customers', 'is_blocked')
    # ### end Alembic commands ###
