"""phase5 sla and routing

Revision ID: 909746e48292
Revises: 'd4e1b34d14ca'
Create Date: 2026-08-20 16:35:56.501890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '909746e48292'
down_revision: Union[str, None] = 'd4e1b34d14ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('conversations', sa.Column('sla_status', sa.String(length=50), server_default='none', nullable=False))
    op.add_column('conversations', sa.Column('first_response_time_seconds', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_conversations_sla_due_at'), 'conversations', ['sla_due_at'], unique=False)
    op.create_index(op.f('ix_conversations_sla_status'), 'conversations', ['sla_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_sla_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_sla_due_at'), table_name='conversations')
    op.drop_column('conversations', 'first_response_time_seconds')
    op.drop_column('conversations', 'sla_status')
    op.drop_column('conversations', 'sla_due_at')
    # ### end Alembic commands ###
