"""phase6 customer 360 timeline and notes

Revision ID: 2baef409438a
Revises: '909746e48292'
Create Date: 2026-08-20 16:45:39.848180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2baef409438a'
down_revision: Union[str, None] = '909746e48292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_notes_author_user_id'), 'customer_notes', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_customer_notes_created_at'), 'customer_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_customer_notes_customer_id'), 'customer_notes', ['customer_id'], unique=False)
    op.create_table('customer_timeline_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=50), server_default='system', nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_timeline_events_created_at'), 'customer_timeline_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_customer_timeline_events_customer_id'), 'customer_timeline_events', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_timeline_events_event_type'), 'customer_timeline_events', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_timeline_events_event_type'), table_name='customer_timeline_events')
    op.drop_index(op.f('ix_customer_timeline_events_customer_id'), table_name='customer_timeline_events')
    op.drop_index(op.f('ix_customer_timeline_events_created_at'), table_name='customer_timeline_events')
    op.drop_table('customer_timeline_events')
    op.drop_index(op.f('ix_customer_notes_customer_id'), table_name='customer_notes')
    op.drop_index(op.f('ix_customer_notes_created_at'), table_name='customer_notes')
    op.drop_index(op.f('ix_customer_notes_author_user_id'), table_name='customer_notes')
    op.drop_table('customer_notes')
    # ### end Alembic commands ###
