"""add_social_comments_tables

Revision ID: b57db77d7a85
Revises: 'f5a1c8e92031'
Create Date: 2026-08-23 18:18:39.358372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b57db77d7a85'
down_revision: Union[str, None] = 'f5a1c8e92031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_moderation_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=True),
    sa.Column('comment_author', sa.String(length=255), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('performed_by', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_moderation_logs_action_type'), 'comment_moderation_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_comment_moderation_logs_comment_id'), 'comment_moderation_logs', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_moderation_logs_created_at'), 'comment_moderation_logs', ['created_at'], unique=False)
    op.create_table('comment_moderation_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('auto_delete_negative', sa.Boolean(), nullable=False),
    sa.Column('auto_hide_spam', sa.Boolean(), nullable=False),
    sa.Column('auto_reply_inquiries', sa.Boolean(), nullable=False),
    sa.Column('strictness_level', sa.String(length=50), nullable=False),
    sa.Column('action_for_negative', sa.String(length=50), nullable=False),
    sa.Column('negative_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('inquiry_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('inquiry_reply_text', sa.Text(), nullable=False),
    sa.Column('inquiry_dm_text', sa.Text(), nullable=False),
    sa.Column('negative_dm_apology_text', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_moderation_settings_brand'), 'comment_moderation_settings', ['brand'], unique=True)
    op.create_table('social_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(length=255), server_default='LUXIRA', nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('post_id', sa.String(length=255), nullable=False),
    sa.Column('post_title', sa.String(length=500), nullable=False),
    sa.Column('post_thumbnail', sa.String(length=1000), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_avatar', sa.String(length=1000), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=False),
    sa.Column('sentiment_score', sa.Integer(), nullable=False),
    sa.Column('moderation_status', sa.String(length=50), nullable=False),
    sa.Column('ai_action_reason', sa.Text(), nullable=True),
    sa.Column('auto_replied_text', sa.Text(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('replies_count', sa.Integer(), nullable=False),
    sa.Column('is_direct_message_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_comments_brand'), 'social_comments', ['brand'], unique=False)
    op.create_index(op.f('ix_social_comments_created_at'), 'social_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_social_comments_moderation_status'), 'social_comments', ['moderation_status'], unique=False)
    op.create_index(op.f('ix_social_comments_platform'), 'social_comments', ['platform'], unique=False)
    op.create_index(op.f('ix_social_comments_post_id'), 'social_comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_social_comments_sentiment'), 'social_comments', ['sentiment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_comments_sentiment'), table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_post_id'), table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_platform'), table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_moderation_status'), table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_created_at'), table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_brand'), table_name='social_comments')
    op.drop_table('social_comments')
    op.drop_index(op.f('ix_comment_moderation_settings_brand'), table_name='comment_moderation_settings')
    op.drop_table('comment_moderation_settings')
    op.drop_index(op.f('ix_comment_moderation_logs_created_at'), table_name='comment_moderation_logs')
    op.drop_index(op.f('ix_comment_moderation_logs_comment_id'), table_name='comment_moderation_logs')
    op.drop_index(op.f('ix_comment_moderation_logs_action_type'), table_name='comment_moderation_logs')
    op.drop_table('comment_moderation_logs')
    # ### end Alembic commands ###
