"""add_social_comments_and_automation_actions

Revision ID: b11f26f22418
Revises: 'c7e908f1a234'
Create Date: 2026-08-21 14:12:35.417292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b11f26f22418'
down_revision: Union[str, None] = 'c7e908f1a234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.String(length=255), nullable=False),
    sa.Column('post_title', sa.String(length=500), nullable=True),
    sa.Column('post_url', sa.Text(), nullable=True),
    sa.Column('comment_id', sa.String(length=255), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_id', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('auto_replied', sa.Boolean(), nullable=False),
    sa.Column('reply_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_comments_author_id'), 'social_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_social_comments_brand'), 'social_comments', ['brand'], unique=False)
    op.create_index(op.f('ix_social_comments_comment_id'), 'social_comments', ['comment_id'], unique=True)
    op.create_index(op.f('ix_social_comments_created_at'), 'social_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_social_comments_post_id'), 'social_comments', ['post_id'], unique=False)
    op.add_column('automation_rules', sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('automation_rules', 'actions')
    op.drop_index(op.f('ix_social_comments_post_id'), table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_created_at'), table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_comment_id'), table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_brand'), table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_author_id'), table_name='social_comments')
    op.drop_table('social_comments')
    # ### end Alembic commands ###
