"""add_post_metadata_and_dm_tracking_to_social_comments

Revision ID: dcb1aa2c6d0b
Revises: 'b11f26f22418'
Create Date: 2026-08-21 16:33:43.868180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcb1aa2c6d0b'
down_revision: Union[str, None] = 'b11f26f22418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_comments', sa.Column('post_thumbnail', sa.Text(), nullable=True))
    op.add_column('social_comments', sa.Column('dm_thread_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_social_comments_dm_thread_id'), 'social_comments', ['dm_thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_comments_dm_thread_id'), table_name='social_comments')
    op.drop_column('social_comments', 'dm_thread_id')
    op.drop_column('social_comments', 'post_thumbnail')
    # ### end Alembic commands ###
