"""p1_add_last_customer_message_at_and_agent_fk

Revision ID: b6c5908d0c93
Revises: 'd5f309cd42a4'
Create Date: 2026-08-20 23:50:46.784591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c5908d0c93'
down_revision: Union[str, None] = 'd5f309cd42a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('last_customer_message_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_conversations_last_customer_message_at'), 'conversations', ['last_customer_message_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_last_customer_message_at'), table_name='conversations')
    op.drop_column('conversations', 'last_customer_message_at')
    # ### end Alembic commands ###
