"""add_customer_fields_and_conversation_brand

Revision ID: 21c90ecf7c48
Revises: 'dcb1aa2c6d0b'
Create Date: 2026-08-21 19:38:31.842590

Note (Task 11 reconciliation): reparented from c7e908f1a234 onto dcb1aa2c6d0b
to linearize a forked chain, and every upgrade operation is guarded by an
existence check so replaying against databases that already contain these
columns/indexes is a safe no-op.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


def _cols(conn, table):
    return {c["name"] for c in inspect(conn).get_columns(table)}


def _idx(conn, table):
    return {i["name"] for i in inspect(conn).get_indexes(table)}


# revision identifiers, used by Alembic.
revision: str = '21c90ecf7c48'
down_revision: Union[str, None] = 'dcb1aa2c6d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    if "brand" not in _cols(conn, "conversations"):
        op.add_column('conversations', sa.Column('brand', sa.String(length=255), server_default='LAVVA', nullable=True))
    idx = _idx(conn, "conversations")
    if "ix_conversations_assigned_agent_id" not in idx:
        op.create_index(op.f('ix_conversations_assigned_agent_id'), 'conversations', ['assigned_agent_id'], unique=False)
    if "ix_conversations_brand" not in idx:
        op.create_index(op.f('ix_conversations_brand'), 'conversations', ['brand'], unique=False)
    cust = _cols(conn, "customers")
    guarded_columns = {
        'location': sa.Column('location', sa.String(length=255), nullable=True),
        'country': sa.Column('country', sa.String(length=255), nullable=True),
        'city': sa.Column('city', sa.String(length=255), nullable=True),
        'tier': sa.Column('tier', sa.String(length=100), server_default='درجة أولى', nullable=True),
        'skin_type': sa.Column('skin_type', sa.String(length=100), server_default='عادية', nullable=True),
        'stage': sa.Column('stage', sa.String(length=100), server_default='جديد', nullable=True),
    }
    for name, col in guarded_columns.items():
        if name not in cust:
            op.add_column('customers', col)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'stage')
    op.drop_column('customers', 'skin_type')
    op.drop_column('customers', 'tier')
    op.drop_column('customers', 'city')
    op.drop_column('customers', 'country')
    op.drop_column('customers', 'location')
    op.drop_index(op.f('ix_conversations_brand'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_assigned_agent_id'), table_name='conversations')
    op.drop_column('conversations', 'brand')
    # ### end Alembic commands ###
