"""add_customer_blocked_fields

Revision ID: f2bd2246d1d0
Revises: '21c90ecf7c48'
Create Date: 2026-08-21 19:48:51.232280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2bd2246d1d0'
down_revision: Union[str, None] = '21c90ecf7c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('is_blocked', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('customers', sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('blocked_reason', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_customers_is_blocked'), 'customers', ['is_blocked'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_is_blocked'), table_name='customers')
    op.drop_column('customers', 'blocked_reason')
    op.drop_column('customers', 'blocked_at')
    op.drop_column('customers', 'is_blocked')
    # ### end Alembic commands ###
