"""phase4 workforce governance

Revision ID: d4e1b34d14ca
Revises: 'c4f9a02b6e12'
Create Date: 2026-08-20 16:25:34.304577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4e1b34d14ca'
down_revision: Union[str, None] = 'c4f9a02b6e12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_audit_logs_action'), 'user_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_user_audit_logs_created_at'), 'user_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_audit_logs_resource_type'), 'user_audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_user_audit_logs_user_id'), 'user_audit_logs', ['user_id'], unique=False)
    op.create_table('conversation_assignment_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by_user_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=True),
    sa.Column('previous_agent_id', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_assignment_logs_assigned_to_user_id'), 'conversation_assignment_logs', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_conversation_assignment_logs_conversation_id'), 'conversation_assignment_logs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_assignment_logs_created_at'), 'conversation_assignment_logs', ['created_at'], unique=False)
    op.add_column('messages', sa.Column('sender_user_id', sa.UUID(), nullable=True))
    op.alter_column('messages', 'message_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('TEXT', 'IMAGE', 'VIDEO', 'AUDIO', 'FILE', 'SHARE_REEL', 'SHARE_POST', 'SYSTEM', 'UNKNOWN', name='messagetypeenum', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_messages_sender_user_id'), 'messages', ['sender_user_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'users', ['sender_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active_at')
    op.drop_column('users', 'last_login_at')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_sender_user_id'), table_name='messages')
    op.alter_column('messages', 'message_type',
               existing_type=sa.Enum('TEXT', 'IMAGE', 'VIDEO', 'AUDIO', 'FILE', 'SHARE_REEL', 'SHARE_POST', 'SYSTEM', 'UNKNOWN', name='messagetypeenum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('messages', 'sender_user_id')
    op.drop_index(op.f('ix_conversation_assignment_logs_created_at'), table_name='conversation_assignment_logs')
    op.drop_index(op.f('ix_conversation_assignment_logs_conversation_id'), table_name='conversation_assignment_logs')
    op.drop_index(op.f('ix_conversation_assignment_logs_assigned_to_user_id'), table_name='conversation_assignment_logs')
    op.drop_table('conversation_assignment_logs')
    op.drop_index(op.f('ix_user_audit_logs_user_id'), table_name='user_audit_logs')
    op.drop_index(op.f('ix_user_audit_logs_resource_type'), table_name='user_audit_logs')
    op.drop_index(op.f('ix_user_audit_logs_created_at'), table_name='user_audit_logs')
    op.drop_index(op.f('ix_user_audit_logs_action'), table_name='user_audit_logs')
    op.drop_table('user_audit_logs')
    # ### end Alembic commands ###
