"""add avatar_url and locale to customers

Revision ID: 1a1af5e52720
Revises: 'e806e52f3382'
Create Date: 2026-08-18 14:00:22.613199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a1af5e52720'
down_revision: Union[str, None] = 'e806e52f3382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('avatar_url', sa.String(length=1000), nullable=True))
    op.add_column('customers', sa.Column('locale', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'locale')
    op.drop_column('customers', 'avatar_url')
    # ### end Alembic commands ###
