"""add_customer_fields_and_conversation_brand

Revision ID: 21c90ecf7c48
Revises: 'c7e908f1a234'
Create Date: 2026-08-21 19:38:31.842590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21c90ecf7c48'
down_revision: Union[str, None] = 'c7e908f1a234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('brand', sa.String(length=255), server_default='LAVVA', nullable=True))
    op.create_index(op.f('ix_conversations_assigned_agent_id'), 'conversations', ['assigned_agent_id'], unique=False)
    op.create_index(op.f('ix_conversations_brand'), 'conversations', ['brand'], unique=False)
    op.add_column('customers', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('country', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('tier', sa.String(length=100), server_default='درجة أولى', nullable=True))
    op.add_column('customers', sa.Column('skin_type', sa.String(length=100), server_default='عادية', nullable=True))
    op.add_column('customers', sa.Column('stage', sa.String(length=100), server_default='جديد', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'stage')
    op.drop_column('customers', 'skin_type')
    op.drop_column('customers', 'tier')
    op.drop_column('customers', 'city')
    op.drop_column('customers', 'country')
    op.drop_column('customers', 'location')
    op.drop_index(op.f('ix_conversations_brand'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_assigned_agent_id'), table_name='conversations')
    op.drop_column('conversations', 'brand')
    # ### end Alembic commands ###
