"""harden_message_uniqueness_constraint

Revision ID: ae36308c1d8f
Revises: '4080a9bea7e9'
Create Date: 2026-08-17 00:08:10.463727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae36308c1d8f'
down_revision: Union[str, None] = '4080a9bea7e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_message_conversation_ext_msg_id', 'messages', ['conversation_id', 'external_message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_message_conversation_ext_msg_id', 'messages', type_='unique')
    # ### end Alembic commands ###
