"""add assigned_agent_id and priority to conversations

Revision ID: 13d5a9490b93
Revises: 'ae36308c1d8f'
Create Date: 2026-08-18 13:16:20.356829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d5a9490b93'
down_revision: Union[str, None] = 'ae36308c1d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('assigned_agent_id', sa.String(length=255), nullable=True))
    op.add_column('conversations', sa.Column('priority', sa.String(length=50), server_default='normal', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'priority')
    op.drop_column('conversations', 'assigned_agent_id')
    # ### end Alembic commands ###
